# Generated by Django 6.0.6 on 2026-07-07 20:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('INSPECTION', 'Inspection'), ('OBSERVATION', 'Observation'), ('INCIDENT', 'Incident'), ('MAINTENANCE', 'Maintenance')], max_length=30)),
                ('scope', models.CharField(choices=[('VEHICLE', 'Vehicle'), ('TRACTOR', 'Tractor'), ('TANKER', 'Tanker')], max_length=20)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('is_blocking', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CORRECTED', 'Corrected'), ('PENDING_VALIDATION', 'Pending validation'), ('RELEASED', 'Released'), ('CLOSED', 'Closed')], default='OPEN', max_length=30)),
                ('detected_at', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_type', models.CharField(choices=[('DOCUMENT', 'Document'), ('INSPECTION', 'Inspection'), ('INSPECTION_CRITERION_RESULT', 'Inspection criterion result'), ('DEFECT', 'Defect'), ('CORRECTIVE_ACTION', 'Corrective action'), ('MAINTENANCE', 'Maintenance'), ('RETURN_TO_SERVICE', 'Return to service'), ('AVAILABILITY_EVALUATION', 'Availability evaluation'), ('NEXT_TRIP_ELIGIBILITY_EVALUATION', 'Next trip eligibility evaluation')], max_length=50)),
                ('owner_id', models.UUIDField()),
                ('evidence_type', models.CharField(choices=[('FILE', 'File'), ('PHOTO', 'Photo'), ('SIGNATURE', 'Signature'), ('COMMENT', 'Comment'), ('SYSTEM_RECORD', 'System record')], max_length=30)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context', models.CharField(choices=[('PERIODIC', 'Periodic'), ('BEFORE_TRIP', 'Before trip'), ('AFTER_INCIDENT', 'After incident'), ('AFTER_MAINTENANCE', 'After maintenance')], max_length=30)),
                ('inspection_date', models.DateTimeField()),
                ('inspector_name', models.CharField(max_length=255)),
                ('overall_result', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('PASS_WITH_OBSERVATION', 'Pass with observation')], max_length=30)),
                ('comments', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InspectionContextSection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context', models.CharField(choices=[('PERIODIC', 'Periodic'), ('BEFORE_TRIP', 'Before trip'), ('AFTER_INCIDENT', 'After incident'), ('AFTER_MAINTENANCE', 'After maintenance')], max_length=30)),
                ('reference', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InspectionCriterion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('label', models.TextField()),
                ('scope', models.CharField(choices=[('VEHICLE', 'Vehicle'), ('TRACTOR', 'Tractor'), ('TANKER', 'Tanker')], max_length=20)),
                ('creates_defect_if_failed', models.BooleanField(default=False)),
                ('is_blocking_if_failed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InspectionSection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NextTripEligibilityEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evaluated_at', models.DateTimeField()),
                ('result', models.CharField(choices=[('ELIGIBLE', 'Eligible'), ('NOT_ELIGIBLE', 'Not eligible')], max_length=20)),
                ('rule_version', models.CharField(max_length=50)),
                ('source_facts', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('performed_by', models.CharField(max_length=255)),
                ('performed_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('evidence_url', models.URLField(blank=True, null=True)),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrective_actions', to='fleet.defect')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DefectReleaseValidation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20)),
                ('validated_by', models.CharField(max_length=255)),
                ('validated_at', models.DateTimeField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('validation_evidence_url', models.URLField(blank=True, null=True)),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_validations', to='fleet.defect')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='defect',
            name='source_inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defects', to='fleet.inspection'),
        ),
        migrations.CreateModel(
            name='InspectionContextCriterion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=20)),
                ('context_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_criteria', to='fleet.inspectioncontextsection')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='context_criteria', to='fleet.inspectioncriterion')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionCriterionResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail')], max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('context_criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_results', to='fleet.inspectioncontextcriterion')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_results', to='fleet.inspection')),
            ],
        ),
        migrations.AddField(
            model_name='defect',
            name='source_inspection_criterion_result',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defect', to='fleet.inspectioncriterionresult'),
        ),
        migrations.AddField(
            model_name='inspectioncontextsection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='context_sections', to='fleet.inspectionsection'),
        ),
        migrations.CreateModel(
            name='NextTripEligibilityEvaluationReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason_type', models.CharField(choices=[('NOT_IN_FLEET', 'Not in fleet'), ('DOCUMENT_MISSING', 'Document missing'), ('DOCUMENT_EXPIRED', 'Document expired'), ('OPEN_BLOCKING_DEFECT', 'Open blocking defect'), ('OUT_OF_SERVICE', 'Out of service'), ('RETURN_TO_SERVICE_REQUIRED', 'Return to service required')], max_length=50)),
                ('message', models.TextField()),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_reasons', to='fleet.nexttripeligibilityevaluation')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tractor_registration', models.CharField(max_length=50)),
                ('tanker_registration', models.CharField(max_length=50)),
                ('display_registration', models.CharField(editable=False, max_length=120)),
                ('vehicle_coupling_start_date', models.DateField()),
                ('vehicle_coupling_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('OUT_OF_SERVICE', 'Out of service')], default='ACTIVE', max_length=30)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='fleet.carrier')),
            ],
        ),
        migrations.CreateModel(
            name='TankerCompartment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('compartment_number', models.PositiveSmallIntegerField()),
                ('capacity_liters', models.PositiveIntegerField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanker_compartments', to='fleet.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnToService',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('DEFECT', 'Defect'), ('MAINTENANCE', 'Maintenance'), ('DOWNTIME', 'Downtime'), ('INSPECTOR_DECISION', 'Inspector decision'), ('OTHER', 'Other')], max_length=30)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('proposed_by_system', models.BooleanField(default=False)),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('decided_by', models.CharField(blank=True, max_length=255, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('evidence_url', models.URLField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_to_services', to='fleet.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='nexttripeligibilityevaluation',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eligibility_evaluations', to='fleet.vehicle'),
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('VEHICLE', 'Vehicle'), ('TRACTOR', 'Tractor'), ('TANKER', 'Tanker')], max_length=20)),
                ('type', models.CharField(choices=[('PREVENTIVE', 'Preventive'), ('CORRECTIVE', 'Corrective')], max_length=20)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('planned_start_date', models.DateTimeField(blank=True, null=True)),
                ('planned_end_date', models.DateTimeField(blank=True, null=True)),
                ('actual_start_date', models.DateTimeField(blank=True, null=True)),
                ('actual_end_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenances', to='fleet.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='inspection',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='fleet.vehicle'),
        ),
        migrations.CreateModel(
            name='FleetMembership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_date', models.DateField()),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('membership_type', models.CharField(choices=[('SPOT', 'Spot'), ('CONTRACTUAL', 'Contractual')], default='SPOT', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ENDED', 'Ended')], default='ACTIVE', max_length=20)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fleet_memberships', to='fleet.carrier')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fleet_memberships', to='fleet.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Downtime',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('MAINTENANCE', 'Maintenance'), ('DEFECT', 'Defect'), ('INCIDENT', 'Incident'), ('MANUAL_DECISION', 'Manual decision'), ('OTHER', 'Other')], max_length=30)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ENDED', 'Ended')], default='ACTIVE', max_length=20)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='downtimes', to='fleet.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='defect',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defects', to='fleet.vehicle'),
        ),
        migrations.CreateModel(
            name='VehicleAvailabilityEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evaluated_at', models.DateTimeField()),
                ('calculated_result', models.CharField(choices=[('AVAILABLE', 'Available'), ('NOT_AVAILABLE', 'Not available')], max_length=20)),
                ('final_result', models.CharField(choices=[('AVAILABLE', 'Available'), ('NOT_AVAILABLE', 'Not available')], max_length=20)),
                ('rule_version', models.CharField(max_length=50)),
                ('validated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('validation_comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='availability_evaluations', to='fleet.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleAvailabilityEvaluationReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason_type', models.CharField(choices=[('VEHICLE_INACTIVE', 'Véhicule inactif'), ('ACTIVE_DOWNTIME', 'Immobilisation active'), ('OPEN_BLOCKING_DEFECT', 'Défaut bloquant ouvert'), ('ACTIVE_TRIP', 'Voyage en cours')], max_length=50)),
                ('message', models.TextField()),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_reasons', to='fleet.vehicleavailabilityevaluation')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('VEHICLE', 'Vehicle'), ('TRACTOR', 'Tractor'), ('TANKER', 'Tanker')], max_length=20)),
                ('document_type', models.CharField(choices=[('PRODUCT_INSURANCE', 'Product_Assurance'), ('CIVIL_INSURANCE', 'Assurance responsabilité civile'), ('TECHNICAL_INSPECTION', 'Visite technique'), ('TANK_CERTIFICATE', 'Certificat citerne'), ('APPROVAL_CERTIFICATE', 'Agrément'), ('REGISTRATION_CERTIFICATE', 'Carte grise'), ('OTHER', 'Autre')], max_length=100)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='fleet.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='inspectioncontextcriterion',
            constraint=models.UniqueConstraint(fields=('context_section', 'criterion'), name='unique_criterion_per_context_section'),
        ),
        migrations.AddConstraint(
            model_name='inspectioncontextcriterion',
            constraint=models.UniqueConstraint(fields=('context_section', 'reference'), name='unique_criterion_reference_per_context_section'),
        ),
        migrations.AddConstraint(
            model_name='inspectioncriterionresult',
            constraint=models.UniqueConstraint(fields=('inspection', 'context_criterion'), name='unique_result_per_inspection_criterion'),
        ),
        migrations.AddConstraint(
            model_name='inspectioncontextsection',
            constraint=models.UniqueConstraint(fields=('context', 'section'), name='unique_section_per_inspection_context'),
        ),
        migrations.AddConstraint(
            model_name='inspectioncontextsection',
            constraint=models.UniqueConstraint(fields=('context', 'reference'), name='unique_section_reference_per_context'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('tractor_registration', 'tanker_registration', 'vehicle_coupling_end_date'), name='unique_vehicle_coupling_period'),
        ),
        migrations.AddConstraint(
            model_name='tankercompartment',
            constraint=models.UniqueConstraint(fields=('vehicle', 'compartment_number'), name='unique_compartment_number_per_vehicle'),
        ),
    ]
