# Generated by Django 6.0.6 on 2026-07-09 21:11

import apps.fleet.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_vehicle_tanker_manufacture_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledocument',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=apps.fleet.upload_paths.vehicle_document_upload_path),
        ),
    ]
