# Generated by Django 6.0.6 on 2026-07-13 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0010_vehiclemembership_vehiclemembershiprequest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclemembershiprequest',
            name='carrier',
        ),
    ]
