# Generated by Django 6.0.6 on 2026-07-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0011_remove_vehiclemembershiprequest_carrier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('AWAITING_FLEET_ENTRY', 'Awaiting fleet entry'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('OUT_OF_SERVICE', 'Out of service')], default='AWAITING_FLEET_ENTRY', max_length=30),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='tanker_manufacture_year',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='tractor_manufacture_year',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
