# Generated by Django 6.0.6 on 2026-07-18 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0016_rename_inspectionversion_inspectioncontextversion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='inspection_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='fleet.inspectioncontextversion'),
        ),
        migrations.AlterField(
            model_name='inspectioncriterion',
            name='reference',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='inspectioncriterion',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='fleet.inspectionsection'),
        ),
        migrations.AlterField(
            model_name='inspectioncriterionresult',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='fleet.inspectioncriterion'),
        ),
        migrations.AlterField(
            model_name='inspectionsection',
            name='inspection_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='fleet.inspectioncontextversion'),
        ),
        migrations.AlterField(
            model_name='inspectionsection',
            name='reference',
            field=models.CharField(max_length=20),
        ),
    ]
