# Generated by Django 6.0.6 on 2026-07-19 22:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0017_alter_inspection_inspection_version_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InspectionContextVersion',
            new_name='InspectionVersion',
        ),
    ]
