# Generated by Django 6.0.6 on 2026-07-20 00:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fleet",
            "0019_remove_inspectionsection_inspection_version_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name="inspectionsection",
                    name=(
                        "unique_section_reference_"
                        "per_inspection_version"
                    ),
                ),
                migrations.RemoveConstraint(
                    model_name="inspectionsection",
                    name=(
                        "unique_section_code_"
                        "per_inspection_version"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="inspectionsection",
            constraint=models.UniqueConstraint(
                fields=("chapter", "reference"),
                name=(
                    "inspection_section_reference_"
                    "per_chapter_unique"
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="inspectionsection",
            constraint=models.UniqueConstraint(
                fields=("chapter", "code"),
                name=(
                    "inspection_section_code_"
                    "per_chapter_unique"
                ),
            ),
        ),
    ]