# Generated by Django 6.0.6 on 2026-07-20 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0021_alter_inspectionsection_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectioncriterion',
            name='scope',
        ),
    ]
