# Generated by Django 6.0.6 on 2026-07-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0024_remove_defect_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='IN_PROGRESS', max_length=20),
        ),
    ]
