# Generated by Django 6.0.6 on 2026-07-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0028_remove_inspectioncriterionresult_unique_result_per_inspection_criterion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionchapter',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectioncriterion',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionsection',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
