# Generated by Django 6.0.6 on 2026-07-22 22:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0032_inspectionscoringpolicyconfiguration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defect',
            name='is_blocking',
        ),
        migrations.RemoveField(
            model_name='defect',
            name='severity',
        ),
        migrations.RemoveField(
            model_name='defect',
            name='source_type',
        ),
        migrations.AddField(
            model_name='defect',
            name='creation_source',
            field=models.CharField(choices=[('MANUAL', 'Manuel'), ('SYSTEM', 'Automatique')], default='MANUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='defect',
            name='detected_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
