# Generated by Django 6.0.6 on 2026-07-26 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0035_vehicleagepolicyconfiguration_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctiveaction',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20),
        ),
    ]
