# Generated by Django 6.0.6 on 2026-07-26 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0037_remove_defectreleasevalidation_defect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectreleasevalidation',
            name='release_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='validation', to='fleet.defectreleaserequest'),
        ),
    ]
