# Generated by Django 6.0.6 on 2026-08-02 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0046_downtimecause_inspection_criterion_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='returntoservice',
            name='downtime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_to_services', to='fleet.downtime'),
        ),
    ]
