# Generated by Django 6.0.6 on 2026-08-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0048_remove_vehicleavailabilityevaluation_rule_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleavailabilityevaluationreason',
            name='reason_type',
            field=models.CharField(choices=[('VEHICLE_INACTIVE', 'Véhicule inactif'), ('ACTIVE_DOWNTIME', 'Immobilisation active'), ('OPEN_BLOCKING_DEFECT', 'Défaut bloquant ouvert'), ('ACTIVE_TRIP', 'Voyage en cours'), ('NO_ACTIVE_MEMBERSHIP', 'Aucune appartenance active à la flotte')], max_length=50),
        ),
    ]
