

from .availabilities import (
    NextTripEligibilityEvaluationReasonSerializer,
    NextTripEligibilityEvaluationReasonSummarySerializer,
    NextTripEligibilityEvaluationSerializer,
    NextTripEligibilityEvaluationSummarySerializer,
    VehicleAvailabilityEvaluationReasonSerializer,
    VehicleAvailabilityEvaluationReasonSummarySerializer,
    VehicleAvailabilityEvaluationSerializer,
    VehicleAvailabilityEvaluationSummarySerializer,
)
from .carriers import CarrierSerializer

from .defects import (
    DefectSummarySerializer,
    DefectReleaseRequestSerializer,
    DefectReleaseValidationInputSerializer,
    DefectReleaseRequestSubmitSerializer,
    DefectReleaseValidationSerializer,
    DefectSerializer,
)

from .maintenances import (
    MaintenancePolicySerializer,
    MaintenanceComponentSerializer,
    MaintenanceWorkOrderItemSerializer,
    MaintenanceWorkOrderSerializer,
    MaintenanceWorkOrderCompleteInputSerializer,
    MaintenanceWorkOrderCancelInputSerializer,
    MaintenanceScheduleSerializer,
    MaintenanceScheduleCancelInputSerializer,
    MaintenanceScheduleGenerateWorkOrderInputSerializer,
    DefectGenerateWorkOrderInputSerializer,
    MaintenanceWorkOrderItemCreateInputSerializer,
)


from .evidences import (
    EvidenceSerializer,
    EvidenceSummarySerializer,
)
from .inspections import (
    CreateInspectionSerializer,
    GenerateInspectionSheetInputSerializer,
    InspectionChapterSerializer,
    InspectionCriterionResultSerializer,
    InspectionCriterionResultSummarySerializer,
    InspectionCriterionSerializer,
    InspectionCriterionSummarySerializer,
    InspectionLocationInputSerializer,
    InspectionScoringPolicyConfigurationSerializer,
    InspectionSectionSerializer,
    InspectionSectionSummarySerializer,
    InspectionSerializer,
    InspectionVersionSerializer,
    RecordCriterionResultInputSerializer,
)
from .operations import (
    DowntimeCauseSerializer,
    DowntimeSerializer,
    ReturnToServiceSerializer,
    DowntimeCreateInputSerializer,
    ReturnToServiceSummarySerializer,
    ReturnToServiceCreateInputSerializer,
    ReturnToServiceApproveInputSerializer,
    ReturnToServiceRejectInputSerializer,
)
from .vehicles import (
    TankerCompartmentSerializer,
    VehicleAgePolicyConfigurationSerializer,
    VehicleDocumentSerializer,
    VehicleMembershipRequestSerializer,
    VehicleMembershipSerializer,
    VehicleSerializer,
    VehicleManualDowntimeInputSerializer,
)


__all__ = [
    "CarrierSerializer",
    "CarrierSummarySerializer",
    "CorrectiveActionSerializer",
    "CorrectiveActionSummarySerializer",
    "CreateInspectionSerializer",
    "DefectReleaseRequestSubmitSerializer",
    "DefectReleaseRequestSerializer",
    "DefectReleaseValidationInputSerializer",
    "DefectReleaseValidationSerializer",
    "DefectReleaseValidationSummarySerializer",
    "DefectSerializer",
    "DefectSummarySerializer",
    "MaintenancePolicySerializer",
    "MaintenanceComponentSerializer",
    "MaintenanceWorkOrderItemSerializer",
    "MaintenanceWorkOrderSerializer",
    "MaintenanceWorkOrderCompleteInputSerializer",
    "MaintenanceWorkOrderCancelInputSerializer",
    "MaintenanceScheduleSerializer",
    "MaintenanceScheduleCancelInputSerializer",
    "MaintenanceScheduleGenerateWorkOrderInputSerializer",
    "MaintenanceWorkOrderItemCreateInputSerializer",
    "DefectGenerateWorkOrderInputSerializer",
    "DowntimeSerializer",  
    "DowntimeCauseSerializer",
    "DowntimeCreateInputSerializer",
    "EvidenceSerializer",
    "EvidenceSummarySerializer",
    "GenerateInspectionSheetInputSerializer",
    "InspectionChapterSerializer",
    "InspectionCriterionResultSerializer",
    "InspectionCriterionResultSummarySerializer",
    "InspectionCriterionSerializer",
    "InspectionCriterionSummarySerializer",
    "InspectionLocationInputSerializer",
    "InspectionScoringPolicyConfigurationSerializer",
    "InspectionSectionSerializer",
    "InspectionSectionSummarySerializer",
    "InspectionSerializer",
    "InspectionVersionSerializer",
    "MaintenanceSerializer",
    "MaintenanceSummarySerializer",
    "NextTripEligibilityEvaluationReasonSerializer",
    "NextTripEligibilityEvaluationReasonSummarySerializer",
    "NextTripEligibilityEvaluationSerializer",
    "NextTripEligibilityEvaluationSummarySerializer",
    "RecordCriterionResultInputSerializer",
    "ReturnToServiceSerializer",
    "ReturnToServiceSummarySerializer",
    "ReturnToServiceCreateInputSerializer",
    "ReturnToServiceApproveInputSerializer",
    "ReturnToServiceRejectInputSerializer",  
    "TankerCompartmentSerializer",
    "TankerCompartmentSummarySerializer",
    "VehicleAgePolicyConfigurationSerializer",
    "VehicleAvailabilityEvaluationReasonSerializer",
    "VehicleAvailabilityEvaluationReasonSummarySerializer",
    "VehicleAvailabilityEvaluationSerializer",
    "VehicleAvailabilityEvaluationSummarySerializer",
    "VehicleDocumentSerializer",
    "VehicleDocumentSummarySerializer",
    "VehicleMembershipRequestSerializer",
    "VehicleMembershipSerializer",
    "VehicleMembershipSummarySerializer",
    "VehicleSerializer",
    "VehicleSummarySerializer",
    "VehicleManualDowntimeInputSerializer",
]