# Generated by Django 6.0.6 on 2026-07-09 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledocument',
            name='document_type',
            field=models.CharField(choices=[('PRODUCT_INSURANCE', 'Assurance produit'), ('CIVIL_INSURANCE', 'Assurance responsabilité civile'), ('TECHNICAL_INSPECTION', 'Visite technique'), ('TANK_CERTIFICATE', 'Certificat citerne'), ('APPROVAL_CERTIFICATE', 'Agrément'), ('REGISTRATION_CERTIFICATE', 'Carte grise'), ('OTHER', 'Autre')], max_length=100),
        ),
    ]
