# Generated by Django 6.0.6 on 2026-07-09 01:56

import apps.fleet.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_alter_vehicledocument_document_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicledocument',
            name='file_url',
        ),
        migrations.AddField(
            model_name='vehicledocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.fleet.upload_paths.vehicle_document_upload_path),
        ),
    ]
