# Generated by Django 6.0.6 on 2026-07-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_remove_vehicledocument_file_url_vehicledocument_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='tanker_manufacture_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tractor_manufacture_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
