# Generated by Django 6.0.6 on 2026-07-10 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_remove_evidence_uploaded_at_carrier_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='evidence',
            name='deleted_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspectioncontextcriterion',
            name='deleted_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectioncontextcriterion',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspectioncontextsection',
            name='deleted_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectioncontextsection',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspectioncriterion',
            name='deleted_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectioncriterion',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspectionsection',
            name='deleted_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionsection',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicledocument',
            name='deleted_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicledocument',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
