# Generated by Django 6.0.6 on 2026-07-17 01:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0013_vehicleagepolicyconfiguration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_reason', models.TextField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context', models.CharField(choices=[('PERIODIC', 'Periodic'), ('BEFORE_TRIP', 'Before trip'), ('AFTER_INCIDENT', 'After incident'), ('AFTER_MAINTENANCE', 'After maintenance')], max_length=30)),
                ('version', models.CharField(max_length=20)),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['context', '-created_at'],
            },
        ),
       migrations.SeparateDatabaseAndState(
    database_operations=[],
    state_operations=[
        migrations.RemoveConstraint(
            model_name='inspectioncontextsection',
            name='unique_section_per_inspection_context',
        ),
        migrations.RemoveConstraint(
            model_name='inspectioncontextsection',
            name='unique_section_reference_per_context',
        ),
    ],
),
        migrations.AddField(
            model_name='inspectionversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectionversion',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectionversion',
            name='source_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_versions', to='fleet.inspectionversion'),
        ),
        migrations.AddField(
            model_name='inspectionversion',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectioncontextsection',
            name='inspection_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='context_sections', to='fleet.inspectionversion'),
        ),
        migrations.AddConstraint(
            model_name='inspectioncontextsection',
            constraint=models.UniqueConstraint(fields=('inspection_version', 'section'), name='unique_section_per_inspection_version'),
        ),
        migrations.AddConstraint(
            model_name='inspectioncontextsection',
            constraint=models.UniqueConstraint(fields=('inspection_version', 'reference'), name='unique_section_reference_per_inspection_version'),
        ),
   migrations.SeparateDatabaseAndState(
    database_operations=[],
    state_operations=[
        migrations.RemoveField(
            model_name='inspectioncontextsection',
            name='context',
        ),
    ],
),
        migrations.AddConstraint(
            model_name='inspectionversion',
            constraint=models.UniqueConstraint(fields=('context', 'version'), name='unique_inspection_version_per_context'),
        ),
    ]
