# Generated by Django 6.0.6 on 2026-07-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0014_inspectionversion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='context',
            field=models.CharField(choices=[('DAILY_CHECK', 'Contrôle quotidien'), ('PERIODIC', 'Periodic'), ('BEFORE_TRIP', 'Before trip'), ('AFTER_INCIDENT', 'After incident'), ('AFTER_MAINTENANCE', 'After maintenance')], max_length=30),
        ),
        migrations.AlterField(
            model_name='inspectionversion',
            name='context',
            field=models.CharField(choices=[('DAILY_CHECK', 'Contrôle quotidien'), ('PERIODIC', 'Periodic'), ('BEFORE_TRIP', 'Before trip'), ('AFTER_INCIDENT', 'After incident'), ('AFTER_MAINTENANCE', 'After maintenance')], max_length=30),
        ),
    ]
