# Generated by Django 6.0.6 on 2026-07-18 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0015_alter_inspection_context_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InspectionVersion',
            new_name='InspectionContextVersion',
        ),
        migrations.RemoveConstraint(
            model_name='inspectioncontextcriterion',
            name='unique_criterion_per_context_section',
        ),
        migrations.RemoveConstraint(
            model_name='inspectioncontextcriterion',
            name='unique_criterion_reference_per_context_section',
        ),
        migrations.RemoveConstraint(
            model_name='inspectioncontextsection',
            name='unique_section_per_inspection_version',
        ),
        migrations.RemoveConstraint(
            model_name='inspectioncontextsection',
            name='unique_section_reference_per_inspection_version',
        ),
        migrations.AlterModelOptions(
            name='inspectioncriterion',
            options={'ordering': ['reference']},
        ),
        migrations.AlterModelOptions(
            name='inspectionsection',
            options={'ordering': ['reference']},
        ),
        migrations.RemoveConstraint(
            model_name='inspectioncriterionresult',
            name='unique_result_per_inspection_criterion',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='context',
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='fleet.inspectioncontextversion'),
        ),
        migrations.AddField(
            model_name='inspectioncriterion',
            name='reference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inspectioncriterion',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='fleet.inspectionsection'),
        ),
        migrations.AddField(
            model_name='inspectioncriterionresult',
            name='criterion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='results', to='fleet.inspectioncriterion'),
        ),
        migrations.AddField(
            model_name='inspectionsection',
            name='inspection_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='fleet.inspectioncontextversion'),
        ),
        migrations.AddField(
            model_name='inspectionsection',
            name='reference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inspectioncriterion',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inspectionsection',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='inspectioncriterion',
            constraint=models.UniqueConstraint(fields=('section', 'reference'), name='unique_criterion_reference_per_section'),
        ),
        migrations.AddConstraint(
            model_name='inspectioncriterion',
            constraint=models.UniqueConstraint(fields=('section', 'code'), name='unique_criterion_code_per_section'),
        ),
        migrations.AddConstraint(
            model_name='inspectioncriterionresult',
            constraint=models.UniqueConstraint(fields=('inspection', 'criterion'), name='unique_result_per_inspection_criterion'),
        ),
        migrations.AddConstraint(
            model_name='inspectionsection',
            constraint=models.UniqueConstraint(fields=('inspection_version', 'reference'), name='unique_section_reference_per_inspection_version'),
        ),
        migrations.AddConstraint(
            model_name='inspectionsection',
            constraint=models.UniqueConstraint(fields=('inspection_version', 'code'), name='unique_section_code_per_inspection_version'),
        ),
        migrations.RemoveField(
            model_name='inspectioncontextcriterion',
            name='context_section',
        ),
        migrations.RemoveField(
            model_name='inspectioncontextcriterion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='inspectioncontextcriterion',
            name='criterion',
        ),
        migrations.RemoveField(
            model_name='inspectioncontextcriterion',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='inspectioncontextcriterion',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='inspectioncriterionresult',
            name='context_criterion',
        ),
        migrations.DeleteModel(
            name='InspectionContextSection',
        ),
        migrations.DeleteModel(
            name='InspectionContextCriterion',
        ),
    ]
