# Generated by Django 6.0.6 on 2026-07-20 00:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0018_rename_inspectioncontextversion_inspectionversion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionsection',
            name='inspection_version',
        ),
        migrations.CreateModel(
            name='InspectionChapter',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_reason', models.TextField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(help_text='Référence du chapitre (I, II, III...).', max_length=10)),
                ('code', models.CharField(help_text='Code technique unique dans une version.', max_length=100)),
                ('title', models.CharField(help_text="Titre affiché sur la fiche d'inspection.", max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Indique si le chapitre est disponible dans cette version.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('inspection_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='fleet.inspectionversion')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['reference'],
            },
        ),
        migrations.AddField(
            model_name='inspectionsection',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='fleet.inspectionchapter'),
        ),
        migrations.AddConstraint(
            model_name='inspectionchapter',
            constraint=models.UniqueConstraint(fields=('inspection_version', 'reference'), name='inspection_chapter_reference_per_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='inspectionchapter',
            constraint=models.UniqueConstraint(fields=('inspection_version', 'code'), name='inspection_chapter_code_per_version_unique'),
        ),
    ]
