# Generated by Django 6.0.6 on 2026-07-20 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0020_remove_inspectionsection_unique_section_reference_per_inspection_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionsection',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='fleet.inspectionchapter'),
        ),
    ]
