# Generated by Django 6.0.6 on 2026-07-20 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0023_alter_inspectioncriterionresult_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defect',
            name='scope',
        ),
    ]
