# Generated by Django 6.0.6 on 2026-07-21 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0029_inspectionchapter_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspectionchapter',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='inspectioncriterion',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='inspectionsection',
            options={'ordering': ['position']},
        ),
    ]
