# Generated by Django 6.0.6 on 2026-07-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0033_remove_defect_is_blocking_remove_defect_severity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='creation_source',
            field=models.CharField(choices=[('SYSTEM', 'Créé par le système'), ('USER', 'Créé par un utilisateur')], default='USER', max_length=20),
        ),
    ]
