# Generated by Django 6.0.6 on 2026-07-26 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0038_alter_defectreleasevalidation_release_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectreleaserequest',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_defect_release_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
