# Generated by Django 6.0.6 on 2026-07-29 01:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0040_alter_defectreleasevalidation_validated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectreleaserequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='MaintenancePolicy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_reason', models.TextField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('interval_days', models.PositiveIntegerField(blank=True, null=True)),
                ('interval_mileage', models.PositiveBigIntegerField(blank=True, null=True)),
                ('interval_engine_hours', models.PositiveBigIntegerField(blank=True, null=True)),
                ('tolerance_days', models.PositiveIntegerField(default=0)),
                ('tolerance_mileage', models.PositiveBigIntegerField(default=0)),
                ('tolerance_engine_hours', models.PositiveBigIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_reason', models.TextField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('due_mileage', models.PositiveBigIntegerField(blank=True, null=True)),
                ('due_engine_hours', models.PositiveBigIntegerField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_schedules', to='fleet.maintenancepolicy')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_schedules', to='fleet.vehicle')),
            ],
            options={
                'ordering': ('due_at', 'due_mileage', 'due_engine_hours'),
            },
        ),
        migrations.CreateModel(
            name='MaintenanceWorkOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_reason', models.TextField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('PREVENTIVE', 'Préventive'), ('CORRECTIVE', 'Corrective')], max_length=20)),
                ('status', models.CharField(choices=[('PLANNED', 'Planifié'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], default='PLANNED', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('planned_start_at', models.DateTimeField(blank=True, null=True)),
                ('planned_end_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('defect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_work_orders', to='fleet.defect')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='fleet.maintenanceschedule')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_work_orders', to='fleet.vehicle')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.DeleteModel(
            name='Maintenance',
        ),
        migrations.AddConstraint(
            model_name='maintenancepolicy',
            constraint=models.CheckConstraint(condition=models.Q(('interval_days__isnull', False), ('interval_mileage__isnull', False), ('interval_engine_hours__isnull', False), _connector='OR'), name='maintenance_policy_requires_interval'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceschedule',
            constraint=models.CheckConstraint(condition=models.Q(('due_at__isnull', False), ('due_mileage__isnull', False), ('due_engine_hours__isnull', False), _connector='OR'), name='maintenance_schedule_requires_due'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceschedule',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('vehicle', 'policy'), name='unique_active_schedule_per_vehicle_policy'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceworkorder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'PREVENTIVE'), ('schedule__isnull', False)), models.Q(('kind', 'CORRECTIVE'), ('schedule__isnull', True)), _connector='OR'), name='maintenance_work_order_schedule_matches_kind'),
        ),
    ]
