# Generated by Django 6.0.6 on 2026-07-29 20:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0042_maintenancecomponent_maintenanceworkorderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='maintenanceworkorder',
            name='maintenance_work_order_schedule_matches_kind',
        ),
        migrations.AddConstraint(
            model_name='maintenanceworkorder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('defect__isnull', True), ('kind', 'PREVENTIVE'), ('schedule__isnull', False)), models.Q(('kind', 'CORRECTIVE'), ('schedule__isnull', True)), _connector='OR'), name='maintenance_work_order_origin_matches_kind'),
        ),
    ]
