# Generated by Django 6.0.6 on 2026-07-30 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0043_remove_maintenanceworkorder_maintenance_work_order_schedule_matches_kind_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenanceworkorder',
            name='started_at',
        ),
        migrations.AlterField(
            model_name='maintenanceworkorder',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planifié'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], default='PLANNED', max_length=20),
        ),
    ]
