# Generated by Django 6.0.6 on 2026-08-01 22:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0044_remove_maintenanceworkorder_started_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DowntimeCause',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_reason', models.TextField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, default='')),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='maintenanceschedule',
            name='unique_active_schedule_per_vehicle_policy',
        ),
        migrations.RemoveField(
            model_name='downtime',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='downtime',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='downtime',
            name='source_type',
        ),
        migrations.AlterField(
            model_name='maintenanceworkorderitem',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='fleet.maintenanceworkorder'),
        ),
        migrations.AlterField(
            model_name='returntoservice',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_to_service_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicleavailabilityevaluation',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validated_vehicle_availability_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='downtime',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True), ('is_deleted', False), ('status', 'ACTIVE')), fields=('vehicle',), name='unique_active_downtime_per_vehicle'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceschedule',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('status', 'ACTIVE')), fields=('vehicle', 'policy'), name='unique_active_schedule_per_vehicle_policy'),
        ),
        migrations.AddField(
            model_name='downtimecause',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='downtimecause',
            name='defect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='downtime_causes', to='fleet.defect'),
        ),
        migrations.AddField(
            model_name='downtimecause',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='downtimecause',
            name='downtime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='causes', to='fleet.downtime'),
        ),
        migrations.AddField(
            model_name='downtimecause',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_downtime_causes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='downtimecause',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
