# Generated by Django 6.0.6 on 2026-08-03 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0047_returntoservice_downtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleavailabilityevaluation',
            name='rule_version',
        ),
    ]
