# Generated by Django 6.0.6 on 2026-08-04 01:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0049_alter_vehicleavailabilityevaluationreason_reason_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleavailabilityevaluation',
            name='evaluated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
