from apps.fleet.views import MaintenanceScheduleViewSet, MaintenanceWorkOrderViewSet, MaintenanceWorkOrderItemViewSet,MaintenanceComponentViewSet,MaintenancePolicyViewSet,CarrierViewSet,DefectReleaseValidationViewSet, DefectViewSet, DowntimeViewSet, EvidenceViewSet, InspectionChapterViewSet, InspectionScoringPolicyConfigurationViewSet, InspectionVersionViewSet, InspectionCriterionResultViewSet, InspectionCriterionViewSet, InspectionSectionViewSet, InspectionViewSet,NextTripEligibilityEvaluationReasonViewSet, NextTripEligibilityEvaluationViewSet, ReturnToServiceViewSet, TankerCompartmentViewSet, VehicleAgePolicyConfigurationViewSet, VehicleAvailabilityEvaluationReasonViewSet, VehicleAvailabilityEvaluationViewSet, VehicleDocumentViewSet, VehicleMembershipRequestViewSet, VehicleMembershipViewSet, VehicleViewSet,DefectReleaseRequestViewSet
from apps.fleet.views.operations import DowntimeCauseViewSet
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register("carriers", CarrierViewSet, basename="carrier")
router.register("vehicle-age-policy-configurations",VehicleAgePolicyConfigurationViewSet,basename="vehicle-age-policy-configuration",)
router.register("vehicles", VehicleViewSet, basename="vehicle")
router.register("tanker-compartments",TankerCompartmentViewSet, basename = "tanker-compartment")
router.register("vehicle-memberships",VehicleMembershipViewSet,basename="vehicle-membership",)
router.register("vehicle-membership-requests",VehicleMembershipRequestViewSet,basename="vehicle-membership-request",)
router.register("vehicle-documents",VehicleDocumentViewSet,basename="vehicle-document",)
router.register("inspection-scoring-policies",InspectionScoringPolicyConfigurationViewSet,basename="inspection-scoring-policy",)
router.register("inspection-versions",InspectionVersionViewSet,basename="inspection-version",)
router.register("inspection-chapters",InspectionChapterViewSet,basename="inspection-chapter",)
router.register("inspection-sections",InspectionSectionViewSet,basename="inspection-section",)
router.register("inspection-criteria",InspectionCriterionViewSet,basename="inspection-criterion",)
router.register("inspections",InspectionViewSet,basename="inspection",)
router.register("inspection-criterion-results",InspectionCriterionResultViewSet,basename="inspection-criterion-result",)
router.register("defects",DefectViewSet,basename="defect",)
router.register("defect-release-requests",DefectReleaseRequestViewSet,basename="defect-release-request",)
router.register("defect-release-validations",DefectReleaseValidationViewSet,basename="defect-release-validation",)
router.register("maintenance-policies",MaintenancePolicyViewSet,basename="maintenance-policy",)
router.register("maintenance-components",MaintenanceComponentViewSet,basename="maintenance-component",)
router.register("maintenance-work-order-items",MaintenanceWorkOrderItemViewSet,basename="maintenance-work-order-item",)
router.register("maintenance-work-orders",MaintenanceWorkOrderViewSet,basename="maintenance-work-order",)
router.register("maintenance-schedules",MaintenanceScheduleViewSet,basename="maintenance-schedule",)
router.register("downtimes",DowntimeViewSet,basename="downtime",)
router.register("downtime-causes",DowntimeCauseViewSet,basename="downtime-cause",)
router.register("return-to-services",ReturnToServiceViewSet,basename="return-to-service",)
router.register("vehicle-availability-evaluations",VehicleAvailabilityEvaluationViewSet,basename="vehicle-availability-evaluation",)
router.register("vehicle-availability-evaluation-reasons",VehicleAvailabilityEvaluationReasonViewSet,basename="vehicle-availability-evaluation-reason",)
router.register("next-trip-eligibility-evaluations",NextTripEligibilityEvaluationViewSet,basename="next-trip-eligibility-evaluation",)
router.register("next-trip-eligibility-evaluation-reasons",NextTripEligibilityEvaluationReasonViewSet,basename="next-trip-eligibility-evaluation-reason",)
router.register("evidences",EvidenceViewSet,basename="evidence",)

urlpatterns = router.urls